permissions:
  contents: write

name: Scrape Talk Locations
on:
  push:
    paths:
      - 'talks/**'
      - '_data/**'
      - 'talkmap.ipynb'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Pre-sync with remote
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin master
          git rebase origin/master || true   # 先把本地快进到最新

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter pandas requests beautifulsoup4 geopy

      - name: Run Jupyter Notebook
        run: |
          jupyter nbconvert --to notebook --execute talkmap.ipynb --output talkmap_out.ipynb

      - name: Commit & push
        run: |
          git add -A
          git commit -m "Automated update of talk locations" || echo "No changes to commit"
          git push
